name: Python CI

on:
  push:
    branches:
      - main  # Or any branch you want to trigger the workflow on
  pull_request:
    branches:
      - main  # Or any branch you want to trigger the workflow on

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]  # List of Python versions to test

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          make install

      - name: Run tests
        run: |
          make test  # Replace with your testing command (e.g., pytest, unittest)

